### ISSUE TITLE
Maven, really executable and trampoline not working with Capsule 1.0

### ISSUE THREAD

**Issue by circlespainter** [danthegoodman/gradle-capsule-plugin#12]
Sample project: https://github.com/circlespainter/capsule-1.0-sample

Resolution doesn't work; it looks like the Maven capsule task is using an older Maven caplet (`1.0-rc1` I think) but forcing it with the `capsule` configuration will just embed the Maven caplet JAR twice.

Really executable capsules and trampolines don't seem to work, the capsule-building tasks print:

```
[ant:concat] /home/fabio/.m2/repository/co/paralleluniverse/capsule/1.0/capsule-1.0.jar:capsule/execheader.sh does not exist.
```

**Comment by danthegoodman** [comment]
You would need to clear and override the `mavenCaplet` configuration; that is where the maven caplet dependency is defined.

And the executable capsules failed since the scripts were moved into 'capsule-util'. 

I'm now working on fixing these for the 1.0 release. Thanks for the heads up!

**Comment by danthegoodman** [comment]
@circlespainter 1.0.0 is out now. I also added a little utility to make it easier to override versions in the future. You can put this somewhere at the beginning of your build file and it will override the builtin version.

```
capsule.version = '1.1'
```

**Comment by cvarona** [comment]
To the best of my knowledge `reallyExecutable { trampoline() }` still does not work in the 1.0.1 version.

`reallyExecutable { script file('src/main/resources/trampoline.sh') }` *does* work, as long the sh file you provide actually exists. Otherwise it will simply build a non-autoexecutable jar, without either failing or issueing any warning.

Regards

**Comment by danthegoodman** [comment]
@cvarona Based upon issue #20, it looks like you need to say `delegate.trampoline()` to make it work. Alternatively, you may use `trampolining()`, which I am going to add in the 1.0.2 version.

As for the silent failure, I've opened another issue and am working on fixing that as well.
