### ISSUE TITLE
Conflict with Closure.trampoline

### ISSUE THREAD

**Issue by mikea** [danthegoodman/gradle-capsule-plugin#20]
ReallyExecutable.trampoline() clashes with Closure.trampoline(). That's why it should be used like this:

    reallyExecutable { delegate.trampoline() }

**Comment by danthegoodman** [comment]
Hmm. That is obviously less than ideal. I think I'll rename it to `trampolining()`. I don't want to do a major version bump here, so I'll keep `trampoline()` and deprecate it.
