### ISSUE TITLE
Could not add resources into jar

### ISSUE THREAD

**Issue by ange1ann** [danthegoodman/gradle-capsule-plugin#32]
the plugin does not include the resources dir,how to fix it?

**Comment by danthegoodman** [comment]
I just created a sample project and the resources ended up in the jar. Maybe something is misconfigured on your end? Do you mind sharing your `build.gradle` file or even your project?

Here is the sample project I created: [foo-project.zip](https://github.com/danthegoodman/gradle-capsule-plugin/files/485181/foo-project.zip)

**Comment by ange1ann** [comment]
[https://github.com/ange1ann/dropwizard-rest](url)
ENV: Gradle, IDEA ,Dropwizard FrameWork
You can see this demo,It does not include dev_config.yml
Use Idea,Just run the command: gradlew build
See The muber-core\build\libs\muber-core-1.0-release.jar

**Comment by danthegoodman** [comment]
<img width="317" alt="screen shot 2016-09-22 at 11 16 00 pm" src="https://cloud.githubusercontent.com/assets/110474/18774067/007f5bdc-811b-11e6-99a2-f05cbe6d2fa0.png">

I was able to build your project successfully, and it shows your yaml file in the jar, along with the other resources added by protobuf. I also opened the project in IDEA 16.2.2 EAP and built the project using the gradle sidebar. That also completed successfully with the resources in the jar file.

When you are running the `build` task, do you see the `processResources` task also run? Does gradle put any files in the `mumber-core/build/resources/main/` directory?

**Comment by ange1ann** [comment]
Theres Two Jar Files In the Dir.
muber-core-1.0.jar(small size)   ---Contains the dev_config.yml file
muber-core-1.0-release.jar(big size)   ---Not Contains the dev_config.yml file
The Release Package Use The classifier:

task fatCapsule(type: FatCapsule) {
    applicationClass mainClassName
    classifier = 'release'
    capsuleManifest {
        systemProperties['dropwizard.config'] = 'dev_config.yml'
        minJavaVersion = '1.8.0'
    }
}
build.dependsOn 'fatCapsule'

You can see that muber-core-1.0-release.jar has no config file.

**Comment by jonas-l** [comment]
@ange1ann, Dropwizard by default expects configuration file to be on a file system, so it should not go into `src/main/resources`. However, you can [configure Dropwizard it to read file from classpath][1] and the issue will go away all together.

[1]: http://stackoverflow.com/a/27012842/25194

**Comment by danthegoodman** [comment]
@ange1ann The release jar is the capsule, which includes the the `muber-core-1.0.jar`and all of your other app dependencies.

If you want the dev_config.yaml to go in the capsule instead of the main jar:

1. Move it to a different directory (like `muber-core/config/dev_config.yml`)
2. Tell the capsule task to include that directory:

```
task fatCapsule(type: FatCapsule) {
    applicationClass mainClassName
    classifier = 'release'
    capsuleManifest {
        systemProperties['dropwizard.config'] = 'dev_config.yml'
        minJavaVersion = '1.8.0'
    }
    from 'config'
}
```

**Comment by ange1ann** [comment]
Thank u for your help!
