### ISSUE TITLE
MavenCapsule fails to configure with a file dependency

### ISSUE THREAD

**Issue by gaborbernat** [danthegoodman/gradle-capsule-plugin#7]
> No signature of method: us.kirchmeier.capsule.manifest.CapsuleManifest.formatModuleDependency() is applicable for argument types: (org.gradle.api.internal.artifacts.dependencies.DefaultSelfResolvingDependency_Decorated) values: [org.gradle.api.internal.artifacts.dependencies.DefaultSelfResolvingDependency_Decorated@433edba9]

At configuration phase I get, any ideas what's wrong? Using Gradle 2.3.

mainClassName = "something"
task slimCapsule(type: MavenCapsule, group: 'that'){
  applicationClass mainClassName
}

**Comment by gaborbernat** [comment]
So, I found the problem, I had a file dependency:

	compile files('lib/upnp.jar')
:) 

It's logic it's not supported, but should be better message provided :)

**Comment by danthegoodman** [comment]
Good idea! I think I'll try and make file based dependencies included in the capsule (fat style). If that's not possible, I'll at least improve the error message.

**Comment by danthegoodman** [comment]
@gaborbernat A MavenCapsule can now handle file dependencies. Thanks for reporting the issue! :smile:
