### ISSUE TITLE
Add custom maven repository to Capsule repo list

### ISSUE THREAD

**Issue by gaborbernat** [danthegoodman/gradle-capsule-plugin#8]
Capsule seems to provide this option, can't see how in Gradle :)

**Comment by danthegoodman** [comment]
Are you looking for [`repositories`](https://github.com/danthegoodman/gradle-capsule-plugin/blob/master/src/main/groovy/us/kirchmeier/capsule/manifest/CapsuleManifest.groovy#L90-L91)?

```groovy
capsuleManifest {
  repositories << 'mavenLocal'
}
```

**Comment by danthegoodman** [comment]
Closed due to inactivity.
